version: '2'
services: 
  server: 
    container_name: express
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/server
    ports:
      - "3001:3001"
    
  client: 
    container_name: react
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/usr/src/client
    ports:
      - "3000:3000"


# Delete failed builds by doing:
  # docker system prune
      